version: '3.2'

services:
    api:
        image: ghcr.io/engineer-man/piston
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec