version: '3.2'

services:
  api:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    privileged: true
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
      - ./data/piston/cache:/piston/cache    # 👈 build cache
    tmpfs:
      - /tmp:exec

  worker:
    image: ghcr.io/engineer-man/piston
    container_name: piston_worker
    restart: always
    privileged: true
    volumes:
      - ./data/piston/packages:/piston/packages
      - ./data/piston/cache:/piston/cache    # 👈 build cache
    tmpfs:
      - /tmp:exec
